x-condition-healthy: &healthy
  condition: service_healthy
x-healthcheck-defaults: &healthcheck-defaults
  interval: 5s
  timeout: 10s
  start_period: 10s
  retries: 5
services:
  web:
    build:
      context: .
      target: development
    ports:
      - "4567:4567"
      - "9394:9394"
    volumes:
      - .:/app
      - gem_cache:/gems
    env_file:
      - env.development
      - .env
  checkout-history:
    image: ghcr.io/mlibrary/checkout-history-unstable:latest
    depends_on:
      checkout-history-db: *healthy
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - MARIADB_ROOT_PASSWORD=password
      - DATABASE_HOST=checkout-history-db
      - SECRET_KEY_BASE=secret_key_base
      - WORKSHOP_AUTH_TOKEN=checkout_history_api_key
      - RAILS_DEVELOPMENT_HOSTS=checkout-history
    env_file:
      - .env
  checkout-history-db:
    image: mariadb
    volumes:
      - checkout_history_db:/var/lib/mysql
    healthcheck:
      !!merge <<: *healthcheck-defaults
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_USER=user
      - MARIADB_PASSWORD=password
      - MARIADB_DATABASE=database
  sass:
    build:
      context: .
      target: development
    volumes:
      - ./css:/app/css
      - ./public/bundles:/app/public/bundles
      - ./package.json:/app/package.json
      - ./node_modules:/app/node_modules
    command: "npm run watch-css"
  esbuild:
    build:
      context: .
      target: development
    volumes:
      - ./js:/app/js
      - ./public/bundles:/app/public/bundles
      - ./package.json:/app/package.json
      - ./node_modules:/app/node_modules
      - ./eslint.config.mjs:/app/eslint.config.mjs
    command: "npm run watch-js"
volumes:
  gem_cache:
  checkout_history_db:
